sudo: false
language: go


go:
  - 1.9.x

git:
  depth: 1

notifications:
  email: false

script:
  - go test -v -race ./... -coverprofile=coverage.txt -covermode=atomic # Run all the tests with the race detector enabled

after_success:
  - bash <(curl -s https://codecov.io/bash)